name: "Reformat Code"

on:
  push:
    branches: ["development"]
  pull_request:
    branches: ["development"]

jobs:
  reformat-code:
    name: "reformat code"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      # Other steps that change files in the repository- name: Laravel Pint
      - name: "laravel-pint"
        uses: aglipanci/laravel-pint-action@2.0.0
        with:
          preset: laravel
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
